title: Gonzalo Iñaki Quintana's Homepage
page-top-title: Gonzalo Iñaki Quintana
top-section-bg-text: Research Scientist
home-subtitle: Gonzalo Iñaki Quintana
copyright-text: '&copy; Gonzalo Iñaki Quintana 2024. All Rights Reserved.'
