title: Gonzalo I単aki Quintana's Homepage
page-top-title: Gonzalo I単aki Quintana
top-section-bg-text: AI Researcher
home-subtitle: Gonzalo I単aki Quintana
copyright-text: '&copy; Gonzalo I単aki Quintana 2024. All Rights Reserved.'
