title: Gonzalo Iñaki Quintana's Homepage
page-top-title: Gonzalo Iñaki Quintana
top-section-bg-text: AI Researcher
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Gonzalo Iñaki Quintana 2024. All Rights Reserved.'
